### PR TITLE
Add option to only pack calldata

### PR DESCRIPTION
**Pull request by benjeffery**
For panoptes import we don't need the variant data in the HDF5. Are you happy with adding an option to only export the calldata such as this?
Ta,
Ben

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @benjeffery, sorry I never actioned this. If it's still useful I'm very happy to merge, would you mind rebasing for a clean merge? Thanks.

**Comment by benjeffery** [comment]
Rebased - I can still see this being useful - at least till I get to the
backend to support full HDF import....

**Comment by alimanfoo** [comment]
Thanks Ben, I'll merge tomorrow.

On Wed, Aug 26, 2015 at 4:40 PM, Ben Jeffery <notifications@github.com>
wrote:

> Rebased - I can still see this being useful - at least till I get to the
> backend to support full HDF import....
>
> On Wed, 26 Aug 2015 at 12:28 Alistair Miles <notifications@github.com>
> wrote:
>
> > Hi @benjeffery <https://github.com/benjeffery>, sorry I never actioned
> > this. If it's still useful I'm very happy to merge, would you mind
> rebasing
> > for a clean merge? Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/alimanfoo/vcfnp/pull/42#issuecomment-134956000>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/vcfnp/pull/42#issuecomment-135070599>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Included in release v2.1.5, thanks @benjeffery.

**Pull request merged**
