### PR TITLE
Region fix (resolves alimanfoo/vcnfp#54)

### PR DESCRIPTION
**Pull request by travc**
Ok... Let me try this again.
This time it is end-to-end tested as best as I can manage...

This should resolve alimanfoo/vcfnp#54
It also includes the minor changes to vcf2hdf5_parallel and therefore resolves alimanfoo/vcfnp#53

The approach is to first skip variants which have a position value < the region's start (if there is a region with a start provided) in `iter.pyx`.

This will change vcfnp behaviour in that iterators created by `itervariants` and `itercalldata` (with a region argument which has a start value) will start with the first variant with a POS in that region, and will not include variants with POS < the region start which none-the-less overlap the region (which is the behaviour of htslib (tabix, vcflib, ect)).

NOTE: I haven't tested the `..._with_condition` functions.  I'm confident `_intervariaints_with_conditions` will work properly since it is almost exactly the same as `_intervariants`, but `_intercalldata_with_conditions` is handled a bit differently.

NOTE 2: I didn't modify `iter.cpp` by hand.  I don't completely understand the python/cython build system, so you might want the version in this pull or you might want to revert it and regenerate it yourself.  I honestly don't know if it matters or not.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Thanks Travis. I'm at ASTMH for the next week but will take a look at this
asap.

On Saturday, October 24, 2015, Travis Collier <notifications@github.com>
wrote:

> Ok... Let me try this again.
> This time it is end-to-end tested as best as I can manage...
>
> This should resolve alimanfoo/vcfnp#54
> <https://github.com/alimanfoo/vcfnp/issues/54>
>
> The approach is to first skip variants which have a position value < the
> region's start (if there is a region with a start provided) in iter.pyx.
>
> This will change vcfnp behaviour in that iterators created by itervariants
> and itercalldata (with a region argument which has a start value) will
> start with the first variant with a POS in that region, and will not
> include variants with POS < the region start which none-the-less overlap
> the region (which is the behaviour of htslib (tabix, vcflib, ect)).
>
> NOTE: I haven't tested the ..._with_condition functions. I'm confident
> _intervariaints_with_conditions will work properly since it is almost
> exactly the same as _intervariants, but _intercalldata_with_conditions is
> handled a bit differently.
>
> NOTE 2: I didn't modify iter.cpp by hand. I don't completely understand
> the python/cython build system, so you might want the version in this pull
> or you might want to revert it and regenerate it yourself. I honestly don't
> know if it matters or not.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/alimanfoo/vcfnp/pull/56
> Commit Summary
>
>    - use shutil.which to get vcf2npy and vcfnpy2hdf5
>    - iterator only includes variants with POS only in range (not just
>    overlapping)
>    - region fix for itercalldata NOTE: ...with_condition not tested
>
> File Changes
>
>    - *M* scripts/vcf2hdf5_parallel
>    <https://github.com/alimanfoo/vcfnp/pull/56/files#diff-0> (6)
>    - *M* vcfnp/iter.cpp
>    <https://github.com/alimanfoo/vcfnp/pull/56/files#diff-1> (4424)
>    - *M* vcfnp/iter.pyx
>    <https://github.com/alimanfoo/vcfnp/pull/56/files#diff-2> (52)
>
> Patch Links:
>
>    - https://github.com/alimanfoo/vcfnp/pull/56.patch
>    - https://github.com/alimanfoo/vcfnp/pull/56.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/vcfnp/pull/56>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by travc** [comment]
No rush.  If I have time, I'll give it more testing by converting some other large vcfs including ones built from mapping to scaffolds (darlingi).
Enjoy Philly

**Comment by alimanfoo** [comment]
Hi Travis, just reviewing this, I think it looks sound but there is a bit of jiggery-pokery to do in making the while loops work properly. Easiest thing I think is if I make some manual changes based on the code in this PR. Thanks again for submitting, will let you know what I do.

**Comment by alimanfoo** [comment]
I've pushed a fix to master based on this PR, closing.

**Pull request closed without merging**
